### ISSUE TITLE
还有用吗？-_-|| 作者停更了。。。

### ISSUE THREAD

**Issue by hacken156026692** [FredyVia/abcd#1]
还有用吗？-_-||
作者停更了。。。

**Comment by FredyVia** [comment]
不知道，正在try，我室友准备自己继续维护




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FredyVia/jd_scripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 上午9:40
收件人:&nbsp;"FredyVia/jd_scripts"<jd_scripts@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FredyVia/jd_scripts] 还有用吗？-_-|| 作者停更了。。。 (#1)





 
还有用吗？-_-||
 作者停更了。。。
